### ISSUE TITLE
When you enable vpn3 does not start the process

### ISSUE THREAD

**Issue by ZoriN89** [schwabe/ics-openvpn#1204]
I try to start the application vpn on vpn3, but the launch does not happen after starting vpn I get the following log
https://pastebin.com/hQhM1HFs
but if you disable vpn3 then the connection passes without problems

**Comment by ZoriN89** [comment]
Config file https://pastebin.com/pfCCXftW

**Comment by schwabe** [comment]
@ZoriN89 could you please send me the source code your app to comply with the GPL?

**Comment by schwabe** [comment]
Also the log does not even match your config file

**Comment by ZoriN89** [comment]
> @ZoriN89 could you please send me the source code your app to comply with the GPL?
I published the source code of the application, https://github.com/ZoriN89/IcsVpnAndroid

I turn on the core vpn3 by indicating the "true" in the file VpnProfile.java line 777

if changed to cfg.write (getConfigFile (context, false)); then the connection will succeed

**Comment by schwabe** [comment]
> package="com.kaylos.moon.vpn"

This has yet another Android package name.

Nothing in this bug report matches. The log does not match the config file and the source code does not match the log. I am not interesting in spending my time debugging other people's apps. (See also https://github.com/schwabe/ics-openvpn/tree/master/doc)

**Comment by ZoriN89** [comment]
> > пакет = "com.kaylos.moon.vpn"
> 
> Это еще одно имя пакета Android.
> 
> Ничто в этом сообщении об ошибке не соответствует. Журнал не соответствует файлу конфигурации, а исходный код не соответствует журналу. Мне не интересно тратить время на отладку приложений других людей. (См. Также https://github.com/schwabe/ics-openvpn/tree/master/doc ).

This is a different package name but it is also my project. I use two the one that is published is ready to work and the one from which I sent the logs at the very beginning it was made to test the functions, I do not have much experience working with Android, so I have a project ready for publication that I published on the github and There is one test on which I check so as not to accidentally break the main one and not fix the problems there.

**Comment by schwabe** [comment]
You also need to publish the sources of the one that is published too.

**Comment by ZoriN89** [comment]
> You also need to publish the sources of the one that is published too.

I don’t understand, do you mean that I need to publish a test version?

**Comment by schwabe** [comment]
The app is under GPL. If you use the source code in any kind of app you need to open source that app too.

**Comment by ZoriN89** [comment]
Got it, I'll publish it now

**Comment by ZoriN89** [comment]
I published a test version as well.
https://github.com/ZoriN89/VpnMoonTest

**Comment by ZoriN89** [comment]
I have installed all the dependencies that are indicated in your readme, swig, ndk, etc. Everything works for me if you do not include ovpn3

**Comment by schwabe** [comment]
@ZoriN89 you don't understand. I don't about your test version. You need to open source the real app not some strange test version of it.

**Comment by ZoriN89** [comment]
The first link that I dropped is the working version of my project, https://github.com/ZoriN89/IcsVpnAndroid

this is my code, and the second I use as a test one. I took the log at the very beginning from the test version, but the same thing happens on the working version.

**Comment by schwabe** [comment]
Whatever you say but it is still not `com.zorin.vpn`. I lost all motivation to help after you obviously not wanting to honour the GPL.

**Comment by ZoriN89** [comment]
> Whatever you say but it is still not com.zorin.vpn. I lost all motivation to help after you obviously not wanting to honour the GPL.


In what sense I didn’t want to, I respected the GPL, I just completed my project, so I attached the log of the test version and put both on the github, I even wrote to you to find out how to comply with the license and what needs to be done and accordingly did everything. These two codes are my one test one and the other one is ready for work and now I decided to convert it to vp3 I posted the log from the test version of the application here, you said put all the code here now, I laid it out, now you say that I do not comply with the license

**Comment by ZoriN89** [comment]
> Whatever you say but it is still not `com.zorin.vpn`. I lost all motivation to help after you obviously not wanting to honour the GPL.

com.zorin.vpn this is a test on my pc, it will not work out anywhere, I check the functions through it and add it to the com.kaylos.moon.vpn that I posted here in accordance with the license, you wrote above that I do not need to upload the test version and did not upload it, I posted the one that was published and added to Play the market (com.kaylos.moon.vpn)

**Comment by ZoriN89** [comment]
> Whatever you say but it is still not `com.zorin.vpn`. I lost all motivation to help after you obviously not wanting to honour the GPL.

You said that I have to put out a working version that I will publish in the play market is com.kaylos.mon.vpn
I published it

now I wanted to update and make support for vpn3 this I did in the test version of the same project but the package is called com.zorin.vpn

I tried to publish com.zorin.vpn but android studio uploads com.kaylos.moon.vpn I downloaded com.zorin.vpn to a mega file exchanger so you can familiarize yourself with it, but I use test com.kaylos.mon.vpn under with the same package it was published in the play market and I laid it out as for com.zorin.vpn this is a test version, I check the function on it as soon as you help with enabling vpn3 i delete it I don’t need it it is a simple copy of the com.kaylos package. mon.vpn. What do I need you to post a finished project that I published in the play market? Or test which is com.zorin.vpn

If you need my project that I use for testing, then here it is https://mega.dp.ua/en/sY7Vh43BN

if I have to publish a project that is in the play market then here it is https://github.com/ZoriN89/IcsVpnAndroid



### com.kaylos.moon.vpn - a working draft which I will add to the play market in compliance with gpl
### com.zorin.vpn - not a working draft but a project for testing the functions that I will add to com.kaylos.moon.vpn

**Comment by schwabe** [comment]
@ZoriN89 I had too many people broken their promises on GPL and also since your app is a commercial app, I don't see why I should be spending my time fixing your app. If you can reproduce the bug with my app, then I can take a look. But looking/fixing other people apps is normally paid consulting work. I do not see why I should work for you for free.
