### ISSUE TITLE
Pixel XL Support

### ISSUE THREAD

**Issue by WalterBVH** [schwabe/ics-openvpn#797]
To make issues more manageable, I would appreciate if you fill out the details if applicable

# General information
1. Android Version 
8.0.0

2. Android Vendor/Custom ROM 
Google

3. Device 
Pixel XL

4. Version of the app (version number/play store version/self built)
0.6.73

# Description of the issue
 
1) When connecting to OpenVPN from my client application, I get a popup "OpenVPN for Android isn't responding." and an ANR from the OpenVPN:
12-04 17:06:35.365 5741-5760/system_process E/ActivityManager: ANR in de.blinkt.openvpn:openvpn
                                                               PID: 10898
                                                               Reason: Context.startForegroundService() did not then call Service.startForeground()

2) When disconnecting from VPN, I get a popup "OpenVPN for Android has stopped" and get the following error: android.os.DeadObjectException
12-04 16:54:17.737 23103-23103/? W/System.err: android.os.DeadObjectException
12-04 16:54:17.737 23103-23103/? W/System.err:     at android.os.BinderProxy.transactNative(Native Method)
12-04 16:54:17.737 23103-23103/? W/System.err:     at android.os.BinderProxy.transact(Binder.java:748)
12-04 16:54:17.737 23103-23103/? W/System.err:     at de.blinkt.openvpn.api.IOpenVPNAPIService$Stub$Proxy.disconnect(IOpenVPNAPIService.java:344)

**Comment by schwabe** [comment]
can you also post the in app log?

When you say "your client application" is that starting via AIDL interface or a modified openvpn for android?

**Comment by WalterBVH** [comment]
starting via AIDL interface, in app log is posted:
[logs.txt](https://github.com/schwabe/ics-openvpn/files/1576785/logs.revised.txt)

**Comment by macdonaldj** [comment]
@schwabe  see logs above

**Comment by schwabe** [comment]
The first trace you posted should be fixed. I cannot reproduce the other one.

**Comment by WalterBVH** [comment]
When you say first trace, are you referring to #1 in the description of the issue?
12-04 17:06:35.365 5741-5760/system_process E/ActivityManager: ANR in de.blinkt.openvpn:openvpn
PID: 10898
Reason: Context.startForegroundService() did not then call Service.startForeground()

Also have you committed the fix to any particular branch?

**Comment by schwabe** [comment]
yes, and no particular branch.

**Comment by WalterBVH** [comment]
I pulled the master branch and had our tester take a look. He was still receiving the ANR in #1. Can you confirm the committed fix?

**Comment by schwabe** [comment]
https://github.com/schwabe/ics-openvpn/commit/597e73a7dacd52145df8b86e53eba743755330a0 is the commit that should fix that issue but maybe you are triggering in a different way.

**Comment by WalterBVH** [comment]
Thanks. I've done some extensive testing with our own application as well as your remoteExample. Our app is calling context.startForegroundService prior to binding to the service in order to allow the VPN to run independently from our application. I saw in the ICS-OpenVPN code, there are 3 services in play. ExternalOpenVPNService, OpenVPNService, and OpenVPNStatusService. I had to add the startForeground() call to each of those services' onCreate event. Those 3 changes fixed all the issues I was getting in Oreo. The catch of course is that an extra notification is displayed for OpenVPN by the call to startForeground. 

Can you find a way to apply these changes to support running OpenVPN in the background on Oreo, while using the same notification that displays when a while connection is active?

**Comment by schwabe** [comment]
why are you starting/bind the externalopenvpnservice with startforeground? shouldn't binding that service with normal priority be enough?

**Comment by WalterBVH** [comment]
We need the VPN service to continue to run if our app has been closed. StartService and startForegroundService(for API 26+) provide this functionality for us. Simply binding the service only keeps the VPN up while our app is open and connected to it and stops the VPN service when our app is closed.

**Comment by schwabe** [comment]
So the real issue here is that the start VPN API of remoteservice does not start the VPN in a way that it survives when the calling app is stopped, do I understand that right?

* Your app starts the VPN via AIDL
* VPN starts and is connected
* Your app stops
* VPN is automatically stopped

Could send me the log of my app in that case? I want to what the VPN logs why it is stopping.

**Comment by WalterBVH** [comment]
I originally added startService to the code to prevent the VPN from stopping back in September. However today, I removed the startService call and I'm no longer able to reproduce the issue of starting the VPN in a way that it doesn't survive when the calling app is stopped. I tried on a few different Android APIs/devices so I'm going to call this fixed. Thanks for your help.
